HBASE-19383 [1.2] java.lang.AssertionError: expected:<2> but was:<1> at org.apache.hadoop.hbase.TestChoreService.testTriggerNowFailsWhenNotScheduled(TestChoreService.java:707)
(cherry picked from commit 94197099952cd09cd36103d79a9dd4e34c191556)

Change-Id: Ia6975a6729f04610c69a1ae5260c588f715ae8f3